apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-git-backend-service
  labels:
    app: git-backend
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.gitBackend.service.additionalAnnotations }}
  annotations:
{{ toYaml .Values.gitBackend.service.additionalAnnotations  | indent 4 }}
  {{- end }}
spec:
  {{ with .Values.gitBackend.service }}
  ports:
  - name: http
    port: {{ .http.port }}
    targetPort: 80
  selector:
    app: git-backend
  type: {{ .type }}
  externalTrafficPolicy: {{ .externalTrafficPolicy }}
  {{- end }}
