apiVersion: v1
kind: Secret
metadata:
  name: openldap-admin
  namespace: openldap
  labels:
    app: gerrit
data:
  adminpassword: #TODO
---
apiVersion: v1
kind: Secret
metadata:
  name: openldap-users
  namespace: openldap
  labels:
    app: gerrit
data:
  users: gerrit-admin,gerrit-user
  passwords: #TODO
